import { ShopItem } from '../types';

export const SHOP_ITEMS: ShopItem[] = [
  // --- BOTAS Y EQUIPAMIENTO ESPECIAL ---
  {
    id: 'gummy_boots',
    name: 'Botas de Gomita Saltarinas',
    category: 'boots',
    price: 350,
    description: '¡Botas mágicas de gelatina dulce superelástica! Aumentan tu altura de salto un +130% de forma permanente y te hacen rebotar elásticamente al tocar el suelo.',
    icon: '🥾',
    color: '#f43f5e',
    badge: '¡SUPER SALTO!',
    world: 'candy',
    jumpMultiplier: 2.3,
  },

  // --- ESPADAS / ARMAS BÁSICAS (VALLE) ---
  {
    id: 'wood_sword',
    name: 'Espada de Madera',
    category: 'sword',
    price: 45,
    description: 'Espada básica de entrenamiento. Aumenta la velocidad base un +15% al sostenerla y permite cortar el aire y derrotar zombis.',
    icon: '🗡️',
    color: '#d97706',
    badge: 'Principiante',
    world: 'main',
    speedMultiplier: 1.15,
    damage: 1,
  },
  {
    id: 'neon_katana',
    name: 'Katana Láser Neón',
    category: 'sword',
    price: 140,
    description: 'Hoja cibernética con filo de plasma cian brillante. +35% de velocidad y rastro de partículas de luz.',
    icon: '⚡',
    color: '#06b6d4',
    badge: 'Popular',
    world: 'main',
    speedMultiplier: 1.35,
    damage: 3,
  },
  {
    id: 'fire_greatsword',
    name: 'Espada Titánica de Fuego',
    category: 'sword',
    price: 320,
    description: 'Espada forjada en lava ardiente. Otorga +50% de velocidad y +30% de altura en todos tus saltos.',
    icon: '🔥',
    color: '#ef4444',
    badge: 'Legendaria',
    world: 'main',
    speedMultiplier: 1.5,
    jumpMultiplier: 1.3,
    damage: 2,
  },

  // --- ESPADAS MEJORES DEL MUNDO CARAMELO ---
  {
    id: 'candy_cane_blade',
    name: 'Espada de Caramelo Afilado',
    category: 'sword',
    price: 240,
    description: 'Hoja de caramelo de menta rayado afilada con azúcar cristalizado puro. Corta el aire con +45% de velocidad y daño x4.',
    icon: '🦯',
    color: '#ef4444',
    badge: 'Mundo Caramelo',
    world: 'candy',
    speedMultiplier: 1.45,
    damage: 4,
  },
  {
    id: 'lollipop_warhammer',
    name: 'Gran Mazo de Piruleta Real',
    category: 'sword',
    price: 490,
    description: 'Mazo colosal forjado con tres capas de caramelo macizo tricolor. Otorga +40% de velocidad, +40% de salto y daño x7 aplastante.',
    icon: '🍭',
    color: '#8b5cf6',
    badge: '¡Gran Daño!',
    world: 'candy',
    speedMultiplier: 1.4,
    jumpMultiplier: 1.4,
    damage: 7,
  },
  {
    id: 'choco_excalibur',
    name: 'Excalibur de Chocolate y Oro',
    category: 'sword',
    price: 850,
    description: 'La legendaria espada bendita del Castillo de Chocolate. Filo de chocolate negro 85% y oro puro. Otorga +75% de velocidad, +60% de salto y daño x12 demoledor contra cualquier jefe.',
    icon: '🍫⚔️',
    color: '#f59e0b',
    badge: '¡SUPREMA!',
    world: 'candy',
    speedMultiplier: 1.75,
    jumpMultiplier: 1.6,
    damage: 12,
  },

  // --- BEBIDAS ENERGÉTICAS (POCIONES) ---
  {
    id: 'speed_drink',
    name: 'Bebida Turbo Sprint',
    category: 'drink',
    price: 30,
    description: 'Bebida isotónica con electrolitos. Acelera tu velocidad de movimiento un +85% durante 35 segundos.',
    icon: '⚡',
    color: '#3b82f6',
    badge: '35 seg',
    durationSec: 35,
    speedMultiplier: 1.85,
  },
  {
    id: 'moon_jump_drink',
    name: 'Bebida Salto Lunar',
    category: 'drink',
    price: 45,
    description: 'Reduce la gravedad corporal. Permite saltar un +90% más alto para escalar cualquier ruina o templo.',
    icon: '🦘',
    color: '#a855f7',
    badge: '35 seg',
    durationSec: 35,
    jumpMultiplier: 1.9,
  },
  {
    id: 'coin_magnet_drink',
    name: 'Bebida Magneto Dorada',
    category: 'drink',
    price: 70,
    description: 'Crea un campo electromagnético que atrae monedas y gemas cercanas automáticamente en un radio de 20m.',
    icon: '🧲',
    color: '#eab308',
    badge: '40 seg',
    durationSec: 40,
    magnetRadius: 20,
  },
  {
    id: 'ultra_energy_drink',
    name: 'Bebida Ultra Híbrida',
    category: 'drink',
    price: 110,
    description: 'La fórmula suprema: activa Súper Velocidad + Súper Salto + Magneto de monedas al mismo tiempo por 45 seg!',
    icon: '🌟',
    color: '#10b981',
    badge: '45 seg MAX',
    durationSec: 45,
    speedMultiplier: 1.7,
    jumpMultiplier: 1.7,
    magnetRadius: 22,
  },
  {
    id: 'soda_pop_drink',
    name: 'Refresco Efervescente de Chicle',
    category: 'drink',
    price: 75,
    description: 'Refresco gaseoso del Mundo Caramelo con burbujas saltarinas. Otorga +100% de velocidad extrema durante 45 segundos.',
    icon: '🥤',
    color: '#ec4899',
    badge: '45 seg Efervescente',
    world: 'candy',
    durationSec: 45,
    speedMultiplier: 2.0,
  },
  {
    id: 'sugar_rush_potion',
    name: 'Elixir de Furia de Azúcar',
    category: 'drink',
    price: 150,
    description: 'Brebaje secreto con néctar de piruleta concentrada. Activa +95% velocidad, +95% salto y +26m magneto de monedas durante 50 segundos.',
    icon: '🍬⚡',
    color: '#f97316',
    badge: '50 seg ÉPICO',
    world: 'candy',
    durationSec: 50,
    speedMultiplier: 1.95,
    jumpMultiplier: 1.95,
    magnetRadius: 26,
  },
];
