import { ShopItem } from '../types';

export const SHOP_ITEMS: ShopItem[] = [
  // --- ESPADAS / ARMAS ---
  {
    id: 'wood_sword',
    name: 'Espada de Madera',
    category: 'sword',
    price: 45,
    description: 'Espada básica de entrenamiento. Aumenta la velocidad base un +15% al sostenerla y permite cortar el aire y derrotar zombis.',
    icon: '🗡️',
    color: '#d97706',
    badge: 'Principiante',
    speedMultiplier: 1.15,
  },
  {
    id: 'neon_katana',
    name: 'Katana Láser Neón',
    category: 'sword',
    price: 140,
    description: 'Hoja cibernética con filo de plasma cian brillante. +35% de velocidad y deja un rastro de partículas de luz.',
    icon: '⚡',
    color: '#06b6d4',
    badge: 'Popular',
    speedMultiplier: 1.35,
  },
  {
    id: 'fire_greatsword',
    name: 'Espada Titánica de Fuego',
    category: 'sword',
    price: 320,
    description: 'Espada forjada en lava ardiente. Otorga +50% de velocidad y +30% de altura en todos tus saltos!',
    icon: '🔥',
    color: '#ef4444',
    badge: 'Legendaria',
    speedMultiplier: 1.5,
    jumpMultiplier: 1.3,
  },

  // --- BEBIDAS ENERGÉTICAS (POCIONES) ---
  {
    id: 'speed_drink',
    name: 'Bebida Turbo Sprint',
    category: 'drink',
    price: 30,
    description: 'Bebida isotónica con electrolitos. Acelera tu velocidad de movimiento un +85% durante 35 segundos.',
    icon: '⚡',
    color: '#3b82f6',
    badge: '35 seg',
    durationSec: 35,
    speedMultiplier: 1.85,
  },
  {
    id: 'moon_jump_drink',
    name: 'Bebida Salto Lunar',
    category: 'drink',
    price: 45,
    description: 'Reduce la gravedad corporal. Permite saltar un +90% más alto para escalar cualquier ruina o templo.',
    icon: '🦘',
    color: '#a855f7',
    badge: '35 seg',
    durationSec: 35,
    jumpMultiplier: 1.9,
  },
  {
    id: 'coin_magnet_drink',
    name: 'Bebida Magneto Dorada',
    category: 'drink',
    price: 70,
    description: 'Crea un campo electromagnético que atrae monedas y gemas cercanas automáticamente en un radio de 20m.',
    icon: '🧲',
    color: '#eab308',
    badge: '40 seg',
    durationSec: 40,
    magnetRadius: 20,
  },
  {
    id: 'ultra_energy_drink',
    name: 'Bebida Ultra Híbrida',
    category: 'drink',
    price: 110,
    description: 'La fórmula suprema: activa Súper Velocidad + Súper Salto + Magneto de monedas al mismo tiempo por 45 seg!',
    icon: '🌟',
    color: '#10b981',
    badge: '45 seg MAX',
    durationSec: 45,
    speedMultiplier: 1.7,
    jumpMultiplier: 1.7,
    magnetRadius: 22,
  },
];
